### ISSUE TITLE
Upgrade to flutter null safe

### ISSUE THREAD

**Issue by champ96k** [loloof64/chess_vectors_flutter#5]
Hello admin can you please assign me I am happy to contribute this amazing package. Thanks

**Comment by loloof64** [comment]
Hello. Thank you for your interest for this package 😃 
I've assigned you (I don't know if i've well done the procedure).

Otherwise, did you noticed that someone contributed in order to solve null safety before ? On this commit
https://github.com/loloof64/chess_vectors_flutter/commit/3fc9c8dc68b07faa51d6dc1334be4ca6888724e7

**Comment by champ96k** [comment]
Okay got it, then I think there is no need to do that again #2 :)

**Comment by loloof64** [comment]
Thank you for your interest 😃 
As a reminder the latest version published on dartpub handles null safety 😃 

https://pub.dev/packages/chess_vectors_flutter/versions
